services:
  epay-bot:
    build: .
    container_name: epay-bot
    restart: always
    volumes:
      - ./config.toml:/app/config.toml
    networks:
      - my_network

networks:
  my_network:
    external: true